# Generated by Django 3.1.8 on 2021-05-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='one_time_pick_up',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pick_up_address',
            field=models.CharField(default='address', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='pick_up_city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='pick_up_date',
            field=models.CharField(default='day', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='pick_up_state',
            field=models.CharField(default='state', max_length=50),
        ),
    ]
