# Generated by Django 3.1.8 on 2021-05-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210509_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='temp_suspend_end',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='temp_suspend_start',
        ),
    ]
