# Generated by Django 3.1.8 on 2021-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210509_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySuspend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspend_date_start', models.DateField(auto_now=True)),
                ('suspend_date_end', models.DateField(auto_now=True)),
            ],
        ),
    ]
