# Generated by Django 3.1.8 on 2021-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_temporarysuspend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporarySuspend',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pick_up_address',
            new_name='pickup_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pick_up_city',
            new_name='pickup_city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pick_up_date',
            new_name='pickup_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pick_up_state',
            new_name='pickup_state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pick_up_zip',
            new_name='pickup_zip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='one_time_pick_up',
        ),
    ]
