# Generated by Django 3.1.8 on 2021-05-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20210512_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
