# Generated by Django 3.1.8 on 2021-05-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20210512_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pickup_state',
            field=models.CharField(default='state', max_length=2),
        ),
    ]
